/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface LszxEmagram {
    'datasrc': string;
  }
  interface LszxEmagramChart {
    'data': any;
  }
  interface LszxEmagramTimeSelector {
    'snapshots': any[];
  }
}

declare namespace LocalJSX {
  interface LszxEmagram extends JSXBase.HTMLAttributes {
    'datasrc'?: string;
  }
  interface LszxEmagramChart extends JSXBase.HTMLAttributes {
    'data'?: any;
  }
  interface LszxEmagramTimeSelector extends JSXBase.HTMLAttributes {
    'onSnapshotSelected'?: (event: CustomEvent<any>) => void;
    'snapshots'?: any[];
  }

  interface IntrinsicElements {
    'lszx-emagram': LszxEmagram;
    'lszx-emagram-chart': LszxEmagramChart;
    'lszx-emagram-time-selector': LszxEmagramTimeSelector;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLLszxEmagramElement extends Components.LszxEmagram, HTMLStencilElement {}
  var HTMLLszxEmagramElement: {
    prototype: HTMLLszxEmagramElement;
    new (): HTMLLszxEmagramElement;
  };

  interface HTMLLszxEmagramChartElement extends Components.LszxEmagramChart, HTMLStencilElement {}
  var HTMLLszxEmagramChartElement: {
    prototype: HTMLLszxEmagramChartElement;
    new (): HTMLLszxEmagramChartElement;
  };

  interface HTMLLszxEmagramTimeSelectorElement extends Components.LszxEmagramTimeSelector, HTMLStencilElement {}
  var HTMLLszxEmagramTimeSelectorElement: {
    prototype: HTMLLszxEmagramTimeSelectorElement;
    new (): HTMLLszxEmagramTimeSelectorElement;
  };

  interface HTMLElementTagNameMap {
    'lszx-emagram': HTMLLszxEmagramElement;
    'lszx-emagram-chart': HTMLLszxEmagramChartElement;
    'lszx-emagram-time-selector': HTMLLszxEmagramTimeSelectorElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

