/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface LsxzEmagramChart {
    'data': any;
  }
  interface LsxzEmagramChartAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }

  interface LsxzEmagram {
    'datasrc': string;
  }
  interface LsxzEmagramAttributes extends StencilHTMLAttributes {
    'datasrc'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LsxzEmagramChart': Components.LsxzEmagramChart;
    'LsxzEmagram': Components.LsxzEmagram;
  }

  interface StencilIntrinsicElements {
    'lsxz-emagram-chart': Components.LsxzEmagramChartAttributes;
    'lsxz-emagram': Components.LsxzEmagramAttributes;
  }


  interface HTMLLsxzEmagramChartElement extends Components.LsxzEmagramChart, HTMLStencilElement {}
  var HTMLLsxzEmagramChartElement: {
    prototype: HTMLLsxzEmagramChartElement;
    new (): HTMLLsxzEmagramChartElement;
  };

  interface HTMLLsxzEmagramElement extends Components.LsxzEmagram, HTMLStencilElement {}
  var HTMLLsxzEmagramElement: {
    prototype: HTMLLsxzEmagramElement;
    new (): HTMLLsxzEmagramElement;
  };

  interface HTMLElementTagNameMap {
    'lsxz-emagram-chart': HTMLLsxzEmagramChartElement
    'lsxz-emagram': HTMLLsxzEmagramElement
  }

  interface ElementTagNameMap {
    'lsxz-emagram-chart': HTMLLsxzEmagramChartElement;
    'lsxz-emagram': HTMLLsxzEmagramElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
